version: '3.8'

services:
  spring-app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://aminebouhaik527:PptvPEwfcUi97KCG@cluster0.hust6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0/ChatApp?retryWrites=true&w=majority
